"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import shutil
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h642jjvc8ptr_u^mjm2h9*)ab4&ayeq6s&h6=k&i(xtmmd@n(#'

# SECURITY WARNING: don't run with debug turned on in production!
# Le de variavel de ambiente: localmente continua True por padrao;
# em producao, definimos DEBUG=False no ambiente do servidor.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Le de variavel de ambiente: localmente continua so localhost/127.0.0.1;
# em producao, definimos ALLOWED_HOSTS com o dominio real no ambiente do servidor.
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',

    'tailwind',
    'theme',

    'apps.portfolio',
    'apps.paginas',
]

TAILWIND_APP_NAME = 'theme'

# No Windows, `npm` é um shim .cmd; subprocess.run sem shell=True não resolve
# o executável sem a extensão explícita, então apontamos o caminho completo.
if os.name == 'nt':
    NPM_BIN_PATH = shutil.which('npm.cmd') or shutil.which('npm')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'logo',
    BASE_DIR / 'imagens',
]

# Pasta pra onde o collectstatic reune os arquivos estaticos em producao.
# Separado de STATICFILES_DIRS (que sao as origens); nao usado pelo runserver local.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Seguranca para producao (HTTPS)
# https://docs.djangoproject.com/en/6.1/topics/security/
#
# So ativa quando DEBUG=False, pra nao quebrar o runserver local (que e HTTP).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Comeca baixo (1h) pra testar antes de aumentar pro valor definitivo.
    SECURE_HSTS_SECONDS = 3600


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
