# Generated by Django 6.1.1 on 2026-09-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao_curta', models.CharField(max_length=300)),
                ('descricao_completa', models.TextField()),
                ('imagem_capa', models.ImageField(upload_to='portfolio/')),
                ('tecnologias', models.CharField(help_text='Separe por vírgula', max_length=300)),
                ('link_projeto', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
